<?php
declare(strict_types=1);
/** @var $block Staempfli\Gdpr\Block\CookieConsent */
?>
<?php if($block->isCookieConsentEnabled()): ?>
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
<script>
    window.addEventListener("load", function(){
        window.cookieconsent.initialise({
            "palette": {
                "popup": {
                    "background": "#000"
                },
                "button": {
                    "background": "#f1d600"
                }
            },
            "position": "top",
            "static": true
        })});
</script>
<?php endif; ?>